// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKs3dm2ZvGTG_dnlCN-N5hw5OQ9CRjlSQ',
    appId: '1:678945314136:web:c3456b03733eb096e1c12d',
    messagingSenderId: '678945314136',
    projectId: 'route-pay-app-958b8',
    authDomain: 'route-pay-app-958b8.firebaseapp.com',
    storageBucket: 'route-pay-app-958b8.appspot.com',
    measurementId: 'G-MQH8RZE804',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOEILBS7s_-OAePfY825EFDLX7j6qH184',
    appId: '1:678945314136:android:831c0f8521f1c88fe1c12d',
    messagingSenderId: '678945314136',
    projectId: 'route-pay-app-958b8',
    storageBucket: 'route-pay-app-958b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQl-fSd3Tz0DFKxpNDh-9Z6EzJ69ZM3A',
    appId: '1:678945314136:ios:3c68eeb1c2667434e1c12d',
    messagingSenderId: '678945314136',
    projectId: 'route-pay-app-958b8',
    storageBucket: 'route-pay-app-958b8.appspot.com',
    iosBundleId: 'com.example.routepayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwQl-fSd3Tz0DFKxpNDh-9Z6EzJ69ZM3A',
    appId: '1:678945314136:ios:7d9b9c1bcc1a0fe0e1c12d',
    messagingSenderId: '678945314136',
    projectId: 'route-pay-app-958b8',
    storageBucket: 'route-pay-app-958b8.appspot.com',
    iosBundleId: 'com.example.routepayapp.RunnerTests',
  );
}
